export type PricingFeature = {
    name: string;
    included: boolean;
};

export type PricingTier = {
    id: string;
    name: string;
    description: string;
    price: number;
    billingPeriod: string;
    quotaLabel?: string;
    quotaOptions?: string[];
    buttonText: string;
    buttonVariant: 'default' | 'outline' | 'blue';
    highlight?: 'cart' | 'popular' | 'none';
    isPremium?: boolean;
    features: PricingFeature[];
};

export const customerServicePlans: PricingTier[] = [
    {
        id: 'cs-free',
        name: 'Free',
        description: 'For new businesses seeking to start offering great customer service for free.',
        price: 0,
        billingPeriod: '/ mo.',
        quotaLabel: '50 billable conversations',
        buttonText: 'Add to order',
        buttonVariant: 'outline',
        highlight: 'cart',
        features: [
            { name: '50 billable conversations', included: true },
            { name: 'Unlimited seats', included: true },
            { name: 'Live Chat', included: true },
            { name: 'Helpdesk system', included: true },
            { name: 'Email management system', included: true },
            { name: 'Live Video calls', included: true },
            { name: 'Messenger integration', included: true },
            { name: 'Instagram integration', included: true },
            { name: 'WhatsApp integration', included: true },
            { name: 'Email integration', included: true },
            { name: 'App integrations', included: true },
            { name: 'Widget customization', included: true },
            { name: 'Custom sending domain', included: true },
            { name: 'Custom email signature', included: true },
            { name: 'Analytics', included: true },
            { name: 'Tidio AI reply assistant', included: true },
            { name: 'Support over email', included: true },
            { name: 'Desktop app', included: true },
            { name: 'Mobile app', included: true },
            { name: 'Multilanguage', included: true },
        ]
    },
    {
        id: 'cs-starter',
        name: 'Starter',
        description: 'Ideal for small businesses focused on enhancing customer satisfaction via live chat support.',
        price: 29,
        billingPeriod: '/ mo.',
        quotaLabel: '100 billable conversations',
        buttonText: 'Add to order',
        buttonVariant: 'blue',
        features: [
            { name: '100 billable conversations', included: true },
            { name: 'Unlimited seats', included: true },
            { name: 'Live Chat', included: true },
            { name: 'Helpdesk system', included: true },
            { name: 'Email management system', included: true },
            { name: 'Live Video calls', included: true },
            { name: 'Messenger integration', included: true },
            { name: 'Instagram integration', included: true },
            { name: 'WhatsApp integration', included: true },
            { name: 'Email integration', included: true },
            { name: 'App integrations', included: true },
            { name: 'Widget customization', included: true },
            { name: 'Custom sending domain', included: true },
            { name: 'Custom email signature', included: true },
            { name: 'Analytics', included: true },
            { name: 'Tidio AI reply assistant', included: true },
            { name: 'Support over email', included: true },
            { name: 'Desktop app', included: true },
            { name: 'Mobile app', included: true },
            { name: 'Multilanguage', included: true },
            { name: 'Live visitors list', included: true },
            { name: 'Operating hours', included: true },
            { name: 'Chat page', included: true }
        ]
    },
    {
        id: 'cs-growth',
        name: 'Growth',
        description: 'Ideal for teams of all sizes prioritizing customer service as their competitive advantage.',
        price: 59,
        billingPeriod: '/ mo.',
        quotaLabel: '250 billable conversations',
        buttonText: 'Add to order',
        buttonVariant: 'blue',
        highlight: 'popular',
        features: [
            { name: 'Up to 2,000 billable conversations', included: true },
            { name: 'Unlimited seats', included: true },
            { name: 'Live Chat', included: true },
            { name: 'Helpdesk system', included: true },
            { name: 'Email management system', included: true },
            { name: 'Live Video calls', included: true },
            { name: 'Messenger integration', included: true },
            { name: 'Instagram integration', included: true },
            { name: 'WhatsApp integration', included: true },
            { name: 'Email integration', included: true },
            { name: 'App integrations', included: true },
            { name: 'Widget customization', included: true },
            { name: 'Custom sending domain', included: true },
            { name: 'Custom email signature', included: true },
            { name: 'Analytics', included: true },
            { name: 'Tidio AI reply assistant', included: true },
            { name: 'Support over email', included: true },
            { name: 'Desktop app', included: true },
            { name: 'Mobile app', included: true },
            { name: 'Multilanguage', included: true },
            { name: 'Live visitors list', included: true },
            { name: 'Operating hours', included: true },
            { name: 'Chat page', included: true },
            { name: 'No Tidio branding (add-on)', included: true },
            { name: 'Live typing', included: true },
            { name: 'Viewed Pages history', included: true },
            { name: 'Visitors info', included: true },
            { name: 'Visitor notes', included: true },
            { name: 'Automatic response', included: true },
            { name: 'Automatic chat assignment', included: true },
            { name: 'Automated satisfaction survey', included: true },
            { name: 'Automated conversation solving', included: true }
        ]
    },
    {
        id: 'cs-plus',
        name: 'Plus',
        description: 'For businesses requiring better limits, additional integrations, advanced features, and premium support.',
        price: 749,
        billingPeriod: '/ mo.',
        buttonText: 'Contact us',
        buttonVariant: 'outline',
        isPremium: true,
        features: [
            { name: 'Custom number of billable conversations', included: true },
            { name: 'Unlimited seats', included: true },
            { name: 'Live Chat', included: true },
            { name: 'Helpdesk system', included: true },
            { name: 'Email management system', included: true },
            { name: 'Live Video calls', included: true },
            { name: 'Messenger integration', included: true },
            { name: 'Instagram integration', included: true },
            { name: 'WhatsApp integration', included: true },
            { name: 'Email integration', included: true },
            { name: 'App integrations', included: true },
            { name: 'Widget customization', included: true },
            { name: 'Custom sending domain', included: true },
            { name: 'Custom email signature', included: true },
            { name: 'Analytics', included: true },
            { name: 'Tidio AI reply assistant', included: true },
            { name: 'Support over email', included: true },
            { name: 'Desktop app', included: true },
            { name: 'Mobile app', included: true },
            { name: 'Multilanguage', included: true },
            { name: 'Live visitors list', included: true },
            { name: 'Operating hours', included: true },
            { name: 'Chat page', included: true },
            { name: 'No Tidio branding', included: true },
            { name: 'Live typing', included: true },
            { name: 'Viewed Pages history', included: true },
            { name: 'Visitors info', included: true },
            { name: 'Visitor notes', included: true },
            { name: 'Automatic response', included: true },
            { name: 'Automatic chat assignment', included: true },
            { name: 'Automated satisfaction survey', included: true },
            { name: 'Automated conversation solving', included: true },
            { name: 'Macros', included: true },
            { name: 'Permissions', included: true },
            { name: 'Native Shopify actions', included: true },
            { name: 'OpenAPI', included: true },
            { name: 'Support over live chat', included: true },
            { name: 'Departments', included: true },
            { name: 'Multisite', included: true },
            { name: 'Custom branding', included: true },
            { name: 'Flow building and strategy assistance', included: true },
            { name: 'Dedicated Customer Success Manager', included: true },
            { name: 'Training sessions', included: true },
            { name: 'Account reviews', included: true },
        ]
    }
];

export const conversaAiPlans: PricingTier[] = [
    {
        id: 'conversa-free',
        name: 'Free',
        description: 'For businesses looking to experience how Conversa AI Agent streamlines their support with 50 free AI-driven conversations.',
        price: 0,
        billingPeriod: '/ mo.',
        quotaLabel: '50 Conversa AI Agent convs',
        buttonText: 'Add to order',
        buttonVariant: 'outline',
        highlight: 'cart',
        features: [
            { name: 'One-time quota of 50 Conversa AI Agent conversations', included: true },
            { name: 'Unlimited seats', included: true },
            { name: 'Live chat integration', included: true },
            { name: 'Messenger integration', included: true },
            { name: 'Instagram integration', included: true },
            { name: 'WhatsApp integration', included: true },
            { name: 'FAQ upload', included: true },
            { name: 'FAQ scraper', included: true },
            { name: 'Website scraper', included: true },
            { name: 'Conversa AI Agent tasks', included: true },
            { name: 'Widget customization', included: true },
            { name: 'Personality customization', included: true },
            { name: 'Support over email', included: true },
        ]
    },
    {
        id: 'conversa-agent',
        name: 'Conversa AI Agent',
        description: 'Ideal for growing businesses aiming to solve up to 70% of customer problems with conversational AI.',
        price: 39,
        billingPeriod: '/ mo.',
        quotaLabel: '50 Conversa AI Agent convs',
        buttonText: 'Add to order',
        buttonVariant: 'blue',
        highlight: 'popular',
        features: [
            { name: 'Up to 1,000 Conversa AI Agent conversations/month', included: true },
            { name: 'Unlimited seats', included: true },
            { name: 'Live chat integration', included: true },
            { name: 'Messenger integration', included: true },
            { name: 'Instagram integration', included: true },
            { name: 'WhatsApp integration', included: true },
            { name: 'FAQ upload', included: true },
            { name: 'FAQ scraper', included: true },
            { name: 'Website scraper', included: true },
            { name: 'Conversa AI Agent tasks', included: true },
            { name: 'Widget customization', included: true },
            { name: 'Personality customization', included: true },
            { name: 'Support over email', included: true },
            { name: 'No Tidio branding (add-on)', included: true },
            { name: 'Conversa product recommendation', included: true },
        ]
    },
    {
        id: 'conversa-plus',
        name: 'Plus',
        description: 'For businesses requiring better limits, additional integrations, advanced features, and premium support.',
        price: 749,
        billingPeriod: '/ mo.',
        buttonText: 'Contact us',
        buttonVariant: 'outline',
        isPremium: true,
        features: [
            { name: 'Custom number of Conversa AI Agent conversations', included: true },
            { name: 'Unlimited seats', included: true },
            { name: 'Live chat integration', included: true },
            { name: 'Messenger integration', included: true },
            { name: 'Instagram integration', included: true },
            { name: 'WhatsApp integration', included: true },
            { name: 'FAQ upload', included: true },
            { name: 'FAQ scraper', included: true },
            { name: 'Website scraper', included: true },
            { name: 'Conversa AI Agent tasks', included: true },
            { name: 'Widget customization', included: true },
            { name: 'Personality customization', included: true },
            { name: 'Support over email', included: true },
            { name: 'No Tidio branding', included: true },
            { name: 'Conversa product recommendation', included: true },
            { name: 'Support over live chat', included: true },
            { name: 'OpenAPI', included: true },
            { name: 'Conversa Connect', included: true },
            { name: 'Custom branding', included: true },
            { name: 'Flow building and strategy assistance', included: true },
            { name: 'Dedicated Customer Success Manager', included: true },
            { name: 'Training sessions', included: true },
            { name: 'Account reviews', included: true },
        ]
    }
];

export const flowsPlans: PricingTier[] = [
    {
        id: 'flows-free',
        name: 'Free',
        description: 'For new businesses aiming to use some automated workflows - free forever, no commitment required.',
        price: 0,
        billingPeriod: '/ mo.',
        quotaLabel: '100 visitors reached',
        buttonText: 'Add to order',
        buttonVariant: 'outline',
        highlight: 'cart',
        features: [
            { name: '100 visitors reached', included: true },
            { name: 'Unlimited seats', included: true },
            { name: 'Messenger integration', included: true },
            { name: 'Instagram integration', included: true },
            { name: 'WhatsApp integration', included: true },
            { name: 'App integrations', included: true },
            { name: 'Widget customization', included: true },
            { name: 'Basic analytics', included: true },
            { name: 'Sales Flows templates', included: true },
            { name: 'FAQ Flows templates', included: true },
            { name: 'Visual Flow builder', included: true },
            { name: 'Support over email', included: true },
            { name: 'Multilanguage', included: true },
        ]
    },
    {
        id: 'flows-paid',
        name: 'Flows',
        description: 'Perfect for businesses of all sizes aiming to save time with sales and support automation.',
        price: 29,
        billingPeriod: '/ mo.',
        quotaLabel: '2,000 visitors reached',
        buttonText: 'Add to order',
        buttonVariant: 'blue',
        highlight: 'popular',
        features: [
            { name: 'Up to 100,000 visitors reached monthly', included: true },
            { name: 'Unlimited seats', included: true },
            { name: 'Messenger integration', included: true },
            { name: 'Instagram integration', included: true },
            { name: 'WhatsApp integration', included: true },
            { name: 'App integrations', included: true },
            { name: 'Widget customization', included: true },
            { name: 'Basic analytics', included: true },
            { name: 'Sales Flows templates', included: true },
            { name: 'FAQ Flows templates', included: true },
            { name: 'Visual Flow builder', included: true },
            { name: 'Support over email', included: true },
            { name: 'Multilanguage', included: true },
            { name: 'No Tidio branding (add-on)', included: true },
        ]
    },
    {
        id: 'flows-plus',
        name: 'Plus',
        description: 'Tailored to businesses looking for custom automation limits, and personalized automation guidance.',
        price: 749,
        billingPeriod: '/ mo.',
        buttonText: 'Contact us',
        buttonVariant: 'outline',
        isPremium: true,
        features: [
            { name: 'Custom number of visitors reached', included: true },
            { name: 'Unlimited seats', included: true },
            { name: 'Messenger integration', included: true },
            { name: 'Instagram integration', included: true },
            { name: 'WhatsApp integration', included: true },
            { name: 'App integrations', included: true },
            { name: 'Widget customization', included: true },
            { name: 'Basic analytics', included: true },
            { name: 'Sales Flows templates', included: true },
            { name: 'FAQ Flows templates', included: true },
            { name: 'Visual Flow builder', included: true },
            { name: 'Support over email', included: true },
            { name: 'Multilanguage', included: true },
            { name: 'No Tidio branding', included: true },
            { name: 'OpenAPI', included: true },
            { name: 'Support over live chat', included: true },
            { name: 'Multisite', included: true },
            { name: 'Custom branding', included: true },
            { name: 'Flow building and strategy assistance', included: true },
            { name: 'Dedicated Customer Success Manager', included: true },
            { name: 'Training sessions', included: true },
            { name: 'Account reviews', included: true },
        ]
    }
];
