/**
 * Flow Templates Library
 * Organized by category: Gather, Nurture, Qualify
 */

export interface FlowTemplate {
    name: string;
    description: string;
    category: 'gather' | 'nurture' | 'qualify' | 'support';
    trigger_type: string;
    is_active: boolean;
    uses?: number;
    nodes: any[];
    edges: any[];
}

// Helper to generate unique IDs
const node = (id: string, type: string, x: number, y: number, data: any) => ({
    id, type, position: { x, y }, data
});

const edge = (id: string, source: string, target: string) => ({
    id, source, target, type: 'custom'
});

export const flowTemplates: FlowTemplate[] = [
    // ============= GATHER CATEGORY =============
    {
        name: 'Lead Magnet / Subscribe Form',
        description: 'Automate your lead generation and collect visitors\' contact information.',
        category: 'gather',
        trigger_type: 'first_visit',
        is_active: false,
        uses: 66200,
        nodes: [
            node('trigger-1', 'flow_trigger', 400, 80, { label: 'First Visit', subtype: 'first_visit' }),
            node('action-1', 'flow_action', 400, 200, { label: 'Send Message', subtype: 'send_message', config: { message: 'Subscribe now and receive our latest promotions! 🎉' } }),
            node('action-2', 'flow_action', 400, 320, { label: 'Decision Buttons', subtype: 'decision_buttons', config: { buttons: ['Subscribe me', 'No, thanks'] } }),
            node('cond-1', 'flow_condition', 400, 440, { label: 'Check Response', subtype: 'based_on_variable', config: { variable: 'button_clicked', operator: 'equals', value: 'Subscribe me' } }),
            node('action-3', 'flow_action', 250, 560, { label: 'Ask Email', subtype: 'ask_question', config: { question: 'Great! What\'s your email address?' } }),
            node('action-4', 'flow_action', 250, 680, { label: 'Thank You', subtype: 'send_message', config: { message: 'Thanks for subscribing! You\'ll receive our best deals soon. 🎁' } }),
            node('action-5', 'flow_action', 550, 560, { label: 'Close Chat', subtype: 'send_message', config: { message: 'No problem! Let me know if you need any help.' } }),
        ],
        edges: [
            edge('e1', 'trigger-1', 'action-1'),
            edge('e2', 'action-1', 'action-2'),
            edge('e3', 'action-2', 'cond-1'),
            edge('e4', 'cond-1', 'action-3'),
            edge('e5', 'action-3', 'action-4'),
            edge('e6', 'cond-1', 'action-5'),
        ],
    },
    {
        name: 'Lead Generation Bot',
        description: 'Engage and generate more leads. Collect e-mail addresses or phone numbers.',
        category: 'gather',
        trigger_type: 'visitor_clicks_chat',
        is_active: false,
        uses: 94600,
        nodes: [
            node('trigger-1', 'flow_trigger', 400, 80, { label: 'Visitor Clicks Chat', subtype: 'visitor_clicks_chat' }),
            node('action-1', 'flow_action', 400, 200, { label: 'Welcome', subtype: 'send_message', config: { message: 'Hi there! 👋 I\'m here to help you get started.' } }),
            node('action-2', 'flow_action', 400, 320, { label: 'Ask Name', subtype: 'ask_question', config: { question: 'What\'s your name?', variable: 'visitor_name' } }),
            node('action-3', 'flow_action', 400, 440, { label: 'Ask Email', subtype: 'ask_question', config: { question: 'Nice to meet you, {{visitor_name}}! What\'s your email address?', variable: 'visitor_email' } }),
            node('action-4', 'flow_action', 400, 560, { label: 'Ask Phone', subtype: 'ask_question', config: { question: 'And your phone number? (optional)', variable: 'visitor_phone' } }),
            node('action-5', 'flow_action', 400, 680, { label: 'Thank You', subtype: 'send_message', config: { message: 'Perfect! Our team will reach out to you shortly. Is there anything else I can help with?' } }),
        ],
        edges: [
            edge('e1', 'trigger-1', 'action-1'),
            edge('e2', 'action-1', 'action-2'),
            edge('e3', 'action-2', 'action-3'),
            edge('e4', 'action-3', 'action-4'),
            edge('e5', 'action-4', 'action-5'),
        ],
    },
    {
        name: 'Order a Phone Call',
        description: 'Collect phone numbers to reach your customers by phone call or SMS.',
        category: 'gather',
        trigger_type: 'visitor_clicks_chat',
        is_active: false,
        uses: 24300,
        nodes: [
            node('trigger-1', 'flow_trigger', 400, 80, { label: 'Visitor Clicks Chat', subtype: 'visitor_clicks_chat' }),
            node('action-1', 'flow_action', 400, 200, { label: 'Offer Call', subtype: 'send_message', config: { message: 'Would you like us to call you back? 📞' } }),
            node('action-2', 'flow_action', 400, 320, { label: 'Decision', subtype: 'decision_buttons', config: { buttons: ['Yes, call me', 'No thanks'] } }),
            node('cond-1', 'flow_condition', 400, 440, { label: 'Check Response', subtype: 'based_on_variable', config: { variable: 'button_clicked', operator: 'equals', value: 'Yes, call me' } }),
            node('action-3', 'flow_action', 250, 560, { label: 'Ask Phone', subtype: 'ask_question', config: { question: 'What\'s the best number to reach you?', variable: 'phone_number' } }),
            node('action-4', 'flow_action', 250, 680, { label: 'Ask Time', subtype: 'ask_question', config: { question: 'When\'s a good time to call?', variable: 'call_time' } }),
            node('action-5', 'flow_action', 250, 800, { label: 'Confirm', subtype: 'send_message', config: { message: 'Great! We\'ll call you at {{phone_number}} around {{call_time}}. Talk soon! 👋' } }),
            node('action-6', 'flow_action', 550, 560, { label: 'Alternative', subtype: 'send_message', config: { message: 'No problem! Feel free to chat with us here anytime.' } }),
        ],
        edges: [
            edge('e1', 'trigger-1', 'action-1'),
            edge('e2', 'action-1', 'action-2'),
            edge('e3', 'action-2', 'cond-1'),
            edge('e4', 'cond-1', 'action-3'),
            edge('e5', 'action-3', 'action-4'),
            edge('e6', 'action-4', 'action-5'),
            edge('e7', 'cond-1', 'action-6'),
        ],
    },
    {
        name: 'Appointment Booking',
        description: 'Enhance customer convenience and streamline your business operations by integrating this easy-to-use appointment booking solution.',
        category: 'gather',
        trigger_type: 'visitor_says',
        is_active: false,
        uses: 3400,
        nodes: [
            node('trigger-1', 'flow_trigger', 400, 80, { label: 'Visitor Says', subtype: 'visitor_says', config: { keywords: ['book', 'appointment', 'schedule', 'meeting'] } }),
            node('action-1', 'flow_action', 400, 200, { label: 'Welcome', subtype: 'send_message', config: { message: 'I\'d be happy to help you book an appointment! 📅' } }),
            node('action-2', 'flow_action', 400, 320, { label: 'Ask Service', subtype: 'ask_question', config: { question: 'What service are you interested in?', variable: 'service_type' } }),
            node('action-3', 'flow_action', 400, 440, { label: 'Ask Date', subtype: 'ask_question', config: { question: 'What date works best for you?', variable: 'preferred_date' } }),
            node('action-4', 'flow_action', 400, 560, { label: 'Ask Time', subtype: 'ask_question', config: { question: 'And what time would you prefer?', variable: 'preferred_time' } }),
            node('action-5', 'flow_action', 400, 680, { label: 'Ask Contact', subtype: 'ask_question', config: { question: 'What\'s your name and phone number so we can confirm?', variable: 'contact_info' } }),
            node('action-6', 'flow_action', 400, 800, { label: 'Confirm', subtype: 'send_message', config: { message: 'Perfect! We\'ve noted your appointment for {{service_type}} on {{preferred_date}} at {{preferred_time}}. We\'ll send a confirmation shortly! ✅' } }),
        ],
        edges: [
            edge('e1', 'trigger-1', 'action-1'),
            edge('e2', 'action-1', 'action-2'),
            edge('e3', 'action-2', 'action-3'),
            edge('e4', 'action-3', 'action-4'),
            edge('e5', 'action-4', 'action-5'),
            edge('e6', 'action-5', 'action-6'),
        ],
    },
    {
        name: 'Gated Content Download',
        description: 'Enhance user engagement and gather valuable leads while offering a seamless experience of accessing gated resources hassle-free!',
        category: 'gather',
        trigger_type: 'page_visit',
        is_active: false,
        uses: 194,
        nodes: [
            node('trigger-1', 'flow_trigger', 400, 80, { label: 'Page Visit', subtype: 'page_visit', config: { url_contains: '/resources' } }),
            node('action-1', 'flow_action', 400, 200, { label: 'Offer Content', subtype: 'send_message', config: { message: '📚 Want to download our exclusive guide? It\'s free!' } }),
            node('action-2', 'flow_action', 400, 320, { label: 'Decision', subtype: 'decision_buttons', config: { buttons: ['Yes, send it!', 'Maybe later'] } }),
            node('cond-1', 'flow_condition', 400, 440, { label: 'Check Response', subtype: 'based_on_variable', config: { variable: 'button_clicked', operator: 'equals', value: 'Yes, send it!' } }),
            node('action-3', 'flow_action', 250, 560, { label: 'Ask Email', subtype: 'ask_question', config: { question: 'Great! Where should I send it?', variable: 'email' } }),
            node('action-4', 'flow_action', 250, 680, { label: 'Send Link', subtype: 'send_message', config: { message: 'Here\'s your download link: [Download Guide] 📥\n\nCheck your email for more resources!' } }),
            node('action-5', 'flow_action', 550, 560, { label: 'Later', subtype: 'send_message', config: { message: 'No problem! The offer will be here when you\'re ready. 😊' } }),
        ],
        edges: [
            edge('e1', 'trigger-1', 'action-1'),
            edge('e2', 'action-1', 'action-2'),
            edge('e3', 'action-2', 'cond-1'),
            edge('e4', 'cond-1', 'action-3'),
            edge('e5', 'action-3', 'action-4'),
            edge('e6', 'cond-1', 'action-5'),
        ],
    },
    {
        name: 'Book a Call with Calendly',
        description: 'Allow visitors to book appointments seamlessly using a custom Calendly Link.',
        category: 'gather',
        trigger_type: 'visitor_says',
        is_active: false,
        uses: 994,
        nodes: [
            node('trigger-1', 'flow_trigger', 400, 80, { label: 'Visitor Says', subtype: 'visitor_says', config: { keywords: ['schedule', 'call', 'meeting', 'demo'] } }),
            node('action-1', 'flow_action', 400, 200, { label: 'Offer Booking', subtype: 'send_message', config: { message: 'I\'d love to schedule a call with you! 📅' } }),
            node('action-2', 'flow_action', 400, 320, { label: 'Share Link', subtype: 'send_message', config: { message: 'Pick a time that works for you:\n👉 [Book on Calendly](https://calendly.com/your-link)' } }),
            node('action-3', 'flow_action', 400, 440, { label: 'Follow Up', subtype: 'send_message', config: { message: 'Once you\'ve booked, you\'ll receive a confirmation email. See you soon! 🙌' } }),
        ],
        edges: [
            edge('e1', 'trigger-1', 'action-1'),
            edge('e2', 'action-1', 'action-2'),
            edge('e3', 'action-2', 'action-3'),
        ],
    },
    {
        name: 'Virtual Event Magnet',
        description: 'Promote upcoming virtual events, encouraging visitors to share their contact details and reserve their spot.',
        category: 'gather',
        trigger_type: 'first_visit',
        is_active: false,
        uses: 25,
        nodes: [
            node('trigger-1', 'flow_trigger', 400, 80, { label: 'First Visit', subtype: 'first_visit' }),
            node('action-1', 'flow_action', 400, 200, { label: 'Event Promo', subtype: 'send_message', config: { message: '🎉 Don\'t miss our upcoming webinar! Reserve your spot now.' } }),
            node('action-2', 'flow_action', 400, 320, { label: 'Decision', subtype: 'decision_buttons', config: { buttons: ['Reserve my spot', 'Tell me more', 'Not interested'] } }),
            node('cond-1', 'flow_condition', 400, 440, { label: 'Check Interest', subtype: 'based_on_variable', config: { variable: 'button_clicked', operator: 'equals', value: 'Reserve my spot' } }),
            node('action-3', 'flow_action', 200, 560, { label: 'Ask Email', subtype: 'ask_question', config: { question: 'What\'s your email? We\'ll send you the event details.', variable: 'email' } }),
            node('action-4', 'flow_action', 200, 680, { label: 'Confirm', subtype: 'send_message', config: { message: 'You\'re registered! 🎊 Check your inbox for the event link.' } }),
            node('action-5', 'flow_action', 400, 560, { label: 'Details', subtype: 'send_message', config: { message: '📅 Date: Coming Soon\n⏰ Time: TBD\n🎯 Topic: Industry Insights\n\nWant to register?' } }),
            node('action-6', 'flow_action', 600, 560, { label: 'Close', subtype: 'send_message', config: { message: 'No worries! Let me know if you have any questions.' } }),
        ],
        edges: [
            edge('e1', 'trigger-1', 'action-1'),
            edge('e2', 'action-1', 'action-2'),
            edge('e3', 'action-2', 'cond-1'),
            edge('e4', 'cond-1', 'action-3'),
            edge('e5', 'action-3', 'action-4'),
            edge('e6', 'cond-1', 'action-5'),
            edge('e7', 'cond-1', 'action-6'),
        ],
    },

    // ============= NURTURE CATEGORY =============
    {
        name: 'News & Updates',
        description: 'Keep your visitors up to date with your new offers and upcoming events.',
        category: 'nurture',
        trigger_type: 'returning_visitor',
        is_active: false,
        uses: 2100,
        nodes: [
            node('trigger-1', 'flow_trigger', 400, 80, { label: 'Returning Visitor', subtype: 'returning_visitor' }),
            node('action-1', 'flow_action', 400, 200, { label: 'Welcome Back', subtype: 'send_message', config: { message: 'Welcome back! 👋 We have some exciting news to share.' } }),
            node('action-2', 'flow_action', 400, 320, { label: 'Share Update', subtype: 'send_message', config: { message: '🆕 Check out our latest:\n• New product launch\n• Special discount for you\n• Upcoming webinar' } }),
            node('action-3', 'flow_action', 400, 440, { label: 'CTA', subtype: 'decision_buttons', config: { buttons: ['Tell me more', 'Browse products', 'Not now'] } }),
        ],
        edges: [
            edge('e1', 'trigger-1', 'action-1'),
            edge('e2', 'action-1', 'action-2'),
            edge('e3', 'action-2', 'action-3'),
        ],
    },
    {
        name: 'Boost Social Media Presence',
        description: 'Improve your online presence by sharing links to your Instagram and Facebook when you mark a conversation as solved.',
        category: 'nurture',
        trigger_type: 'conversation_solved',
        is_active: false,
        uses: 554,
        nodes: [
            node('trigger-1', 'flow_trigger', 400, 80, { label: 'Conversation Solved', subtype: 'conversation_solved' }),
            node('action-1', 'flow_action', 400, 200, { label: 'Thank You', subtype: 'send_message', config: { message: 'Glad I could help! 🎉' } }),
            node('action-2', 'flow_action', 400, 320, { label: 'Social Invite', subtype: 'send_message', config: { message: 'Stay connected with us for more updates and exclusive content:\n\n📸 Instagram: @yourhandle\n👍 Facebook: /yourpage\n🐦 Twitter: @yourhandle' } }),
            node('action-3', 'flow_action', 400, 440, { label: 'Close', subtype: 'send_message', config: { message: 'Have a great day! Come back anytime. 😊' } }),
        ],
        edges: [
            edge('e1', 'trigger-1', 'action-1'),
            edge('e2', 'action-1', 'action-2'),
            edge('e3', 'action-2', 'action-3'),
        ],
    },
    {
        name: 'Launch Day',
        description: 'Generate excitement and acquire leads for your upcoming product or service. Collects email and name information.',
        category: 'nurture',
        trigger_type: 'first_visit',
        is_active: false,
        uses: 94,
        nodes: [
            node('trigger-1', 'flow_trigger', 400, 80, { label: 'First Visit', subtype: 'first_visit' }),
            node('action-1', 'flow_action', 400, 200, { label: 'Launch Announcement', subtype: 'send_message', config: { message: '🚀 Something BIG is coming! Be the first to know.' } }),
            node('action-2', 'flow_action', 400, 320, { label: 'Interest Check', subtype: 'decision_buttons', config: { buttons: ['Notify me!', 'What is it?', 'Not interested'] } }),
            node('cond-1', 'flow_condition', 400, 440, { label: 'Check Response', subtype: 'based_on_variable', config: { variable: 'button_clicked', operator: 'equals', value: 'Notify me!' } }),
            node('action-3', 'flow_action', 200, 560, { label: 'Ask Name', subtype: 'ask_question', config: { question: 'What\'s your name?', variable: 'name' } }),
            node('action-4', 'flow_action', 200, 680, { label: 'Ask Email', subtype: 'ask_question', config: { question: 'And your email for the VIP list?', variable: 'email' } }),
            node('action-5', 'flow_action', 200, 800, { label: 'Confirm', subtype: 'send_message', config: { message: 'You\'re on the list, {{name}}! 🎉 We\'ll email you first.' } }),
            node('action-6', 'flow_action', 400, 560, { label: 'Teaser', subtype: 'send_message', config: { message: 'It\'s our biggest launch yet... Stay tuned! Want to join the waitlist?' } }),
            node('action-7', 'flow_action', 600, 560, { label: 'Close', subtype: 'send_message', config: { message: 'No problem! Check back soon for the reveal. 👀' } }),
        ],
        edges: [
            edge('e1', 'trigger-1', 'action-1'),
            edge('e2', 'action-1', 'action-2'),
            edge('e3', 'action-2', 'cond-1'),
            edge('e4', 'cond-1', 'action-3'),
            edge('e5', 'action-3', 'action-4'),
            edge('e6', 'action-4', 'action-5'),
            edge('e7', 'cond-1', 'action-6'),
            edge('e8', 'cond-1', 'action-7'),
        ],
    },
    {
        name: 'Mobile App Promoter',
        description: 'Direct users to the appropriate app store for a quick and easy download, ensuring a seamless user experience.',
        category: 'nurture',
        trigger_type: 'first_visit',
        is_active: false,
        uses: 74,
        nodes: [
            node('trigger-1', 'flow_trigger', 400, 80, { label: 'First Visit', subtype: 'first_visit' }),
            node('action-1', 'flow_action', 400, 200, { label: 'App Promo', subtype: 'send_message', config: { message: '📱 Did you know we have a mobile app? Get the best experience on the go!' } }),
            node('action-2', 'flow_action', 400, 320, { label: 'Platform Choice', subtype: 'decision_buttons', config: { buttons: ['iOS / iPhone', 'Android', 'Maybe later'] } }),
            node('cond-1', 'flow_condition', 400, 440, { label: 'Check Platform', subtype: 'based_on_variable', config: { variable: 'button_clicked', operator: 'equals', value: 'iOS / iPhone' } }),
            node('action-3', 'flow_action', 200, 560, { label: 'iOS Link', subtype: 'send_message', config: { message: '🍎 Download for iOS:\n[App Store Link]' } }),
            node('action-4', 'flow_action', 400, 560, { label: 'Android Link', subtype: 'send_message', config: { message: '🤖 Download for Android:\n[Play Store Link]' } }),
            node('action-5', 'flow_action', 600, 560, { label: 'Later', subtype: 'send_message', config: { message: 'No rush! The app will be here when you\'re ready. 😊' } }),
        ],
        edges: [
            edge('e1', 'trigger-1', 'action-1'),
            edge('e2', 'action-1', 'action-2'),
            edge('e3', 'action-2', 'cond-1'),
            edge('e4', 'cond-1', 'action-3'),
            edge('e5', 'cond-1', 'action-4'),
            edge('e6', 'cond-1', 'action-5'),
        ],
    },
    {
        name: 'Article Booster',
        description: 'Increase engagement with articles, gather feedback, while also enticing readers to subscribe to newsletters.',
        category: 'nurture',
        trigger_type: 'page_visit',
        is_active: false,
        uses: 58,
        nodes: [
            node('trigger-1', 'flow_trigger', 400, 80, { label: 'Page Visit', subtype: 'page_visit', config: { url_contains: '/blog' } }),
            node('action-1', 'flow_action', 400, 200, { label: 'Engage Reader', subtype: 'send_message', config: { message: '📖 Enjoying this article? I have more great content for you!' } }),
            node('action-2', 'flow_action', 400, 320, { label: 'Offer Options', subtype: 'decision_buttons', config: { buttons: ['Subscribe to newsletter', 'Show related articles', 'Leave feedback'] } }),
            node('cond-1', 'flow_condition', 400, 440, { label: 'Check Choice', subtype: 'based_on_variable', config: { variable: 'button_clicked', operator: 'equals', value: 'Subscribe to newsletter' } }),
            node('action-3', 'flow_action', 200, 560, { label: 'Ask Email', subtype: 'ask_question', config: { question: 'Great! What\'s your email?', variable: 'email' } }),
            node('action-4', 'flow_action', 200, 680, { label: 'Subscribed', subtype: 'send_message', config: { message: 'You\'re subscribed! 🎉 Check your inbox for the latest.' } }),
            node('action-5', 'flow_action', 400, 560, { label: 'Related', subtype: 'send_message', config: { message: 'You might also like:\n• Article 1\n• Article 2\n• Article 3' } }),
            node('action-6', 'flow_action', 600, 560, { label: 'Feedback', subtype: 'ask_question', config: { question: 'What did you think of this article? Your feedback helps us improve!', variable: 'feedback' } }),
        ],
        edges: [
            edge('e1', 'trigger-1', 'action-1'),
            edge('e2', 'action-1', 'action-2'),
            edge('e3', 'action-2', 'cond-1'),
            edge('e4', 'cond-1', 'action-3'),
            edge('e5', 'action-3', 'action-4'),
            edge('e6', 'cond-1', 'action-5'),
            edge('e7', 'cond-1', 'action-6'),
        ],
    },

    // ============= QUALIFY CATEGORY =============
    {
        name: 'Lead Gen For Beauty',
        description: 'Elevate your lead generation strategy by engaging visitors, offering tailored beauty consultations, and capturing essential information.',
        category: 'qualify',
        trigger_type: 'visitor_clicks_chat',
        is_active: false,
        uses: 172,
        nodes: [
            node('trigger-1', 'flow_trigger', 400, 80, { label: 'Visitor Clicks Chat', subtype: 'visitor_clicks_chat' }),
            node('action-1', 'flow_action', 400, 200, { label: 'Welcome', subtype: 'send_message', config: { message: '✨ Welcome! Looking for beauty tips or ready to book a consultation?' } }),
            node('action-2', 'flow_action', 400, 320, { label: 'Interest', subtype: 'decision_buttons', config: { buttons: ['Book consultation', 'Product recommendations', 'Just browsing'] } }),
            node('cond-1', 'flow_condition', 400, 440, { label: 'Check Intent', subtype: 'based_on_variable', config: { variable: 'button_clicked', operator: 'equals', value: 'Book consultation' } }),
            node('action-3', 'flow_action', 200, 560, { label: 'Skin Type', subtype: 'ask_question', config: { question: 'What\'s your skin type? (Oily, Dry, Combination, Sensitive)', variable: 'skin_type' } }),
            node('action-4', 'flow_action', 200, 680, { label: 'Concerns', subtype: 'ask_question', config: { question: 'Any specific concerns? (Acne, Aging, Pigmentation, etc.)', variable: 'concerns' } }),
            node('action-5', 'flow_action', 200, 800, { label: 'Contact', subtype: 'ask_question', config: { question: 'Perfect! Your name and phone number for the consultation?', variable: 'contact' } }),
            node('action-6', 'flow_action', 200, 920, { label: 'Confirm', subtype: 'send_message', config: { message: 'We\'ll contact you shortly to schedule your personalized consultation! 💄' } }),
            node('action-7', 'flow_action', 500, 560, { label: 'Products', subtype: 'send_message', config: { message: 'Check out our bestsellers:\n• Hydrating Serum\n• Anti-aging Cream\n• Glow Mask' } }),
        ],
        edges: [
            edge('e1', 'trigger-1', 'action-1'),
            edge('e2', 'action-1', 'action-2'),
            edge('e3', 'action-2', 'cond-1'),
            edge('e4', 'cond-1', 'action-3'),
            edge('e5', 'action-3', 'action-4'),
            edge('e6', 'action-4', 'action-5'),
            edge('e7', 'action-5', 'action-6'),
            edge('e8', 'cond-1', 'action-7'),
        ],
    },
    {
        name: 'Request a Quote - Agency',
        description: 'Streamline your agency\'s lead generation by interacting with visitors, understanding their needs, and providing clear paths to request service quotes.',
        category: 'qualify',
        trigger_type: 'visitor_says',
        is_active: false,
        uses: 110,
        nodes: [
            node('trigger-1', 'flow_trigger', 400, 80, { label: 'Visitor Says', subtype: 'visitor_says', config: { keywords: ['quote', 'pricing', 'cost', 'estimate'] } }),
            node('action-1', 'flow_action', 400, 200, { label: 'Greet', subtype: 'send_message', config: { message: 'Thanks for your interest! 🎯 Let me help you get a quote.' } }),
            node('action-2', 'flow_action', 400, 320, { label: 'Service Type', subtype: 'ask_question', config: { question: 'What service are you looking for?\n• Web Development\n• Marketing\n• Design\n• Consulting', variable: 'service' } }),
            node('action-3', 'flow_action', 400, 440, { label: 'Budget', subtype: 'ask_question', config: { question: 'What\'s your approximate budget range?', variable: 'budget' } }),
            node('action-4', 'flow_action', 400, 560, { label: 'Timeline', subtype: 'ask_question', config: { question: 'When do you need this completed?', variable: 'timeline' } }),
            node('action-5', 'flow_action', 400, 680, { label: 'Company', subtype: 'ask_question', config: { question: 'Company name and your role?', variable: 'company' } }),
            node('action-6', 'flow_action', 400, 800, { label: 'Contact', subtype: 'ask_question', config: { question: 'Best email to send the quote to?', variable: 'email' } }),
            node('action-7', 'flow_action', 400, 920, { label: 'Confirm', subtype: 'send_message', config: { message: 'Perfect! Our team will prepare a custom quote and send it to {{email}} within 24 hours. 📧' } }),
        ],
        edges: [
            edge('e1', 'trigger-1', 'action-1'),
            edge('e2', 'action-1', 'action-2'),
            edge('e3', 'action-2', 'action-3'),
            edge('e4', 'action-3', 'action-4'),
            edge('e5', 'action-4', 'action-5'),
            edge('e6', 'action-5', 'action-6'),
            edge('e7', 'action-6', 'action-7'),
        ],
    },
    {
        name: 'Request a Quote - Photo & Video',
        description: 'Simplify booking for photography and videography services by engaging potential clients and capturing their event details directly.',
        category: 'qualify',
        trigger_type: 'visitor_says',
        is_active: false,
        uses: 30,
        nodes: [
            node('trigger-1', 'flow_trigger', 400, 80, { label: 'Visitor Says', subtype: 'visitor_says', config: { keywords: ['photography', 'video', 'shoot', 'wedding', 'event'] } }),
            node('action-1', 'flow_action', 400, 200, { label: 'Welcome', subtype: 'send_message', config: { message: '📸 Excited to hear about your project! Let me gather some details.' } }),
            node('action-2', 'flow_action', 400, 320, { label: 'Event Type', subtype: 'ask_question', config: { question: 'What type of shoot?\n• Wedding\n• Corporate\n• Portrait\n• Product\n• Event', variable: 'event_type' } }),
            node('action-3', 'flow_action', 400, 440, { label: 'Date', subtype: 'ask_question', config: { question: 'When is the event/shoot date?', variable: 'date' } }),
            node('action-4', 'flow_action', 400, 560, { label: 'Location', subtype: 'ask_question', config: { question: 'Where will it take place?', variable: 'location' } }),
            node('action-5', 'flow_action', 400, 680, { label: 'Duration', subtype: 'ask_question', config: { question: 'Estimated duration? (e.g., 2 hours, full day)', variable: 'duration' } }),
            node('action-6', 'flow_action', 400, 800, { label: 'Contact', subtype: 'ask_question', config: { question: 'Your name, email, and phone number?', variable: 'contact' } }),
            node('action-7', 'flow_action', 400, 920, { label: 'Confirm', subtype: 'send_message', config: { message: 'Amazing! I\'ll send you a custom quote for your {{event_type}} shoot. Talk soon! 🎬' } }),
        ],
        edges: [
            edge('e1', 'trigger-1', 'action-1'),
            edge('e2', 'action-1', 'action-2'),
            edge('e3', 'action-2', 'action-3'),
            edge('e4', 'action-3', 'action-4'),
            edge('e5', 'action-4', 'action-5'),
            edge('e6', 'action-5', 'action-6'),
            edge('e7', 'action-6', 'action-7'),
        ],
    },
    {
        name: 'Lead Gen for Agency (Short)',
        description: 'Efficiently capture leads with a concise flow designed for agencies, focusing on quick engagement and essential data collection.',
        category: 'qualify',
        trigger_type: 'visitor_clicks_chat',
        is_active: false,
        uses: 24,
        nodes: [
            node('trigger-1', 'flow_trigger', 400, 80, { label: 'Visitor Clicks Chat', subtype: 'visitor_clicks_chat' }),
            node('action-1', 'flow_action', 400, 200, { label: 'Quick Intro', subtype: 'send_message', config: { message: 'Hey! 👋 Interested in working with us?' } }),
            node('action-2', 'flow_action', 400, 320, { label: 'Service', subtype: 'decision_buttons', config: { buttons: ['Web Development', 'Marketing', 'Design', 'Other'] } }),
            node('action-3', 'flow_action', 400, 440, { label: 'Contact', subtype: 'ask_question', config: { question: 'Drop your email and we\'ll reach out!', variable: 'email' } }),
            node('action-4', 'flow_action', 400, 560, { label: 'Thanks', subtype: 'send_message', config: { message: 'Got it! We\'ll be in touch within 24 hours. 🚀' } }),
        ],
        edges: [
            edge('e1', 'trigger-1', 'action-1'),
            edge('e2', 'action-1', 'action-2'),
            edge('e3', 'action-2', 'action-3'),
            edge('e4', 'action-3', 'action-4'),
        ],
    },
    {
        name: 'Table Booking',
        description: 'Facilitate seamless restaurant reservations by engaging diners and collecting booking details effortlessly.',
        category: 'qualify',
        trigger_type: 'visitor_says',
        is_active: false,
        uses: 67,
        nodes: [
            node('trigger-1', 'flow_trigger', 400, 80, { label: 'Visitor Says', subtype: 'visitor_says', config: { keywords: ['reservation', 'table', 'book', 'dining'] } }),
            node('action-1', 'flow_action', 400, 200, { label: 'Welcome', subtype: 'send_message', config: { message: '🍽️ Great choice! Let me help you book a table.' } }),
            node('action-2', 'flow_action', 400, 320, { label: 'Date', subtype: 'ask_question', config: { question: 'What date would you like to dine with us?', variable: 'date' } }),
            node('action-3', 'flow_action', 400, 440, { label: 'Time', subtype: 'ask_question', config: { question: 'What time?', variable: 'time' } }),
            node('action-4', 'flow_action', 400, 560, { label: 'Party Size', subtype: 'ask_question', config: { question: 'How many guests?', variable: 'party_size' } }),
            node('action-5', 'flow_action', 400, 680, { label: 'Contact', subtype: 'ask_question', config: { question: 'Name and phone number for the reservation?', variable: 'contact' } }),
            node('action-6', 'flow_action', 400, 800, { label: 'Special', subtype: 'ask_question', config: { question: 'Any special requests? (Birthday, anniversary, dietary needs)', variable: 'special' } }),
            node('action-7', 'flow_action', 400, 920, { label: 'Confirm', subtype: 'send_message', config: { message: 'Your table for {{party_size}} on {{date}} at {{time}} is confirmed! 🎉 See you soon!' } }),
        ],
        edges: [
            edge('e1', 'trigger-1', 'action-1'),
            edge('e2', 'action-1', 'action-2'),
            edge('e3', 'action-2', 'action-3'),
            edge('e4', 'action-3', 'action-4'),
            edge('e5', 'action-4', 'action-5'),
            edge('e6', 'action-5', 'action-6'),
            edge('e7', 'action-6', 'action-7'),
        ],
    },
    {
        name: 'Real Estate Quote',
        description: 'Connect with potential property buyers or sellers, engaging them to gather preferences and provide tailored real estate quotes.',
        category: 'qualify',
        trigger_type: 'visitor_clicks_chat',
        is_active: false,
        uses: 45,
        nodes: [
            node('trigger-1', 'flow_trigger', 400, 80, { label: 'Visitor Clicks Chat', subtype: 'visitor_clicks_chat' }),
            node('action-1', 'flow_action', 400, 200, { label: 'Welcome', subtype: 'send_message', config: { message: '🏠 Welcome! Looking to buy or sell property?' } }),
            node('action-2', 'flow_action', 400, 320, { label: 'Intent', subtype: 'decision_buttons', config: { buttons: ['Buy', 'Sell', 'Rent', 'Just curious'] } }),
            node('cond-1', 'flow_condition', 400, 440, { label: 'Check Intent', subtype: 'based_on_variable', config: { variable: 'button_clicked', operator: 'equals', value: 'Buy' } }),
            node('action-3', 'flow_action', 150, 560, { label: 'Property Type', subtype: 'ask_question', config: { question: 'What type of property? (House, Apartment, Land)', variable: 'property_type' } }),
            node('action-4', 'flow_action', 150, 680, { label: 'Location', subtype: 'ask_question', config: { question: 'Preferred location/area?', variable: 'location' } }),
            node('action-5', 'flow_action', 150, 800, { label: 'Budget', subtype: 'ask_question', config: { question: 'What\'s your budget range?', variable: 'budget' } }),
            node('action-6', 'flow_action', 150, 920, { label: 'Contact', subtype: 'ask_question', config: { question: 'Your name and phone to schedule viewings?', variable: 'contact' } }),
            node('action-7', 'flow_action', 150, 1040, { label: 'Confirm', subtype: 'send_message', config: { message: 'Our agent will contact you with matching properties! 🔑' } }),
            node('action-8', 'flow_action', 400, 560, { label: 'Sell Info', subtype: 'ask_question', config: { question: 'What property do you want to sell? (Address or description)', variable: 'property_details' } }),
            node('action-9', 'flow_action', 650, 560, { label: 'Rent Info', subtype: 'ask_question', config: { question: 'Looking to rent in which area?', variable: 'rent_area' } }),
        ],
        edges: [
            edge('e1', 'trigger-1', 'action-1'),
            edge('e2', 'action-1', 'action-2'),
            edge('e3', 'action-2', 'cond-1'),
            edge('e4', 'cond-1', 'action-3'),
            edge('e5', 'action-3', 'action-4'),
            edge('e6', 'action-4', 'action-5'),
            edge('e7', 'action-5', 'action-6'),
            edge('e8', 'action-6', 'action-7'),
            edge('e9', 'cond-1', 'action-8'),
            edge('e10', 'cond-1', 'action-9'),
        ],
    },

    // ============= SUPPORT CATEGORY =============
    {
        name: 'FAQ RAG Assistant',
        description: 'Answer questions using your knowledge base with AI-powered retrieval.',
        category: 'support',
        trigger_type: 'visitor_says',
        is_active: false,
        uses: 15000,
        nodes: [
            node('trigger-1', 'flow_trigger', 400, 80, { label: 'Visitor Says', subtype: 'visitor_says' }),
            node('rag-1', 'flow_rag', 400, 200, { label: 'Embed Query', subtype: 'embed_query', category: 'retrieval', config: { input_variable: '{{message_text}}' } }),
            node('rag-2', 'flow_rag', 400, 320, { label: 'Vector Search', subtype: 'vector_search', category: 'retrieval', config: { top_k: 5, min_score: 0.7 } }),
            node('rag-3', 'flow_rag', 400, 440, { label: 'Context Builder', subtype: 'context_builder', category: 'retrieval', config: { format: 'numbered' } }),
            node('rag-4', 'flow_rag', 400, 560, { label: 'LLM Call', subtype: 'llm_call', category: 'llm', config: { model: 'sarvam', temperature: 0.7 } }),
            node('action-1', 'flow_action', 400, 680, { label: 'Send Response', subtype: 'send_message', config: { message: '{{llm_response}}' } }),
        ],
        edges: [
            edge('e1', 'trigger-1', 'rag-1'),
            edge('e2', 'rag-1', 'rag-2'),
            edge('e3', 'rag-2', 'rag-3'),
            edge('e4', 'rag-3', 'rag-4'),
            edge('e5', 'rag-4', 'action-1'),
        ],
    },
    {
        name: 'Welcome Message',
        description: 'Greet new visitors when they first visit your site.',
        category: 'support',
        trigger_type: 'first_visit',
        is_active: true,
        uses: 50000,
        nodes: [
            node('trigger-1', 'flow_trigger', 400, 100, { label: 'First Visit', subtype: 'first_visit' }),
            node('action-1', 'flow_action', 400, 250, { label: 'Send Message', subtype: 'send_message', config: { message: 'Hi there! 👋 Welcome to our site. How can I help you today?' } }),
        ],
        edges: [
            edge('e1', 'trigger-1', 'action-1'),
        ],
    },
];

// Helper to get templates by category
export function getTemplatesByCategory(category: string): FlowTemplate[] {
    if (category === 'all') return flowTemplates;
    return flowTemplates.filter(t => t.category === category);
}
